### PR TITLE
Draft: Add (still failing) tests for "unselect all" button functionality

### PR DESCRIPTION
**Pull request by jmuheim**
Related to #38.

All tests pass, except 2:

CleanShot 2022-04-30 at 11 29 45@2x

When the bug is fixed, the tests should pass. 👍

Wow, I just had an AHA-effect - it's probably the first time that I do BDD (behaviour driven testing) with that! 😃

### CODE REVIEW

**Comment by jmuheim** [comment]
Just adding a screenshot here of what **not** should happen.

Multi-Select:

CleanShot 2022-05-01 at 14 40 22@2x

Single-Select:

CleanShot 2022-05-01 at 14 41 41@2x

There obviously is no filter term anymore, but the options are still filtered according to a term.

**Comment by rudigier** [comment]
@jmuheim Ist nun angepasst.

**Comment by jmuheim** [comment]
@rudigier The tests fail because when having an **empty filter** and then selecting an option, the combobox announces:

> 1 von 10 Farben für Filter "black"

Although it should be:

> 1 von 10 Farben

CleanShot 2022-05-02 at 07 49 21@2x

We should really start working in dedicated branches now. I have pulled your changes in `main`, and merged them into the branch here. Please apply any changes here, to keep `main` clean. 🙏

**Comment by jmuheim** [comment]
I'm taking a close look at this now.

**Comment by jmuheim** [comment]
Fixed 👍

CleanShot 2022-05-02 at 15 54 21@2x

**Pull request merged**
